### ISSUE TITLE
Correct CUDA Driver URLProvider

### ISSUE THREAD

**Issue by jessepeterson** [jessepeterson/autopkg-recipes#2]
To use this update URL:

https://partners.download.nvidia.com/activation/cuda_update_macos.xml

This is the URL that the CUDA Driver pref pane uses to check for updates. Integrate with URL Provider.

**Comment by timsutton** [comment]
Yeah, a while back I started collecting info I'd need to write a URL provider to parse this, and never got around to it. Their update framework uses Google's keystone updater system.

If you use this, you also have the advantage of getting OS compatibility metadata in the form of an NSPredicate, using the value for `SystemVersion.ProductVersion`.

So far I've only seen granularity down to major OS versions like `10.7`, `10.8`. So, an added processor could set the min. and max. OS versions in the pkginfo according to iterative evaluations of the predicate. ie. try 10.6, 10.7, 10.8, etc. to build the list of OS compatible versions for each update offered in the feed.

My thinking on this was that a recipe could then take a default 'target' OS version set to whatever's the current most recent shipping version of OS to use for evaluating the predicate, and also accept an alternate OS version as an override. This way you could specify '10.6' for this overridden value and it would automatically pull the older version that's available and set the appropriate OS constraints in the pkginfo.

It's not like there are a lot of updates, but there will of course be more branches in the future assuming they keep this update mechanism. (And since Google wrote it, it works :)

**Comment by jessepeterson** [comment]
I'm not too familiar with Keystone—but you're saying this XML is a "standard" schema? So there'd be a KeystoneURLProvider (a la SparkleURLProvider?)

**Comment by jessepeterson** [comment]
I didn't look hard enough—it's a plist!

**Comment by jessepeterson** [comment]
So, you're thinking something like this?

``` python
if 'cuda_os_ver' not in self.env:
    cuda_os_ver = self.env['cuda_os_ver']
else:
    cuda_os_ver = '10.8.5'

predicate.evaluateWithObject_({'Ticket': {'Version': ''}, 'SystemVersion': {'ProductVersion': cuda_os_ver}})
```

**Comment by jessepeterson** [comment]
Let me know what you think about that commit. Seems to be working for me.

**Comment by timsutton** [comment]
This is great!

The only other idea I had in the comments I made earlier, was that since this is a Munki recipe, and the feed info provides (indirectly) info about what versions of OS X are compatible with the update, you could convert these to `minimum_os_version` and `maximum_os_version` keys as well. I think the cleanest way would be to simply evaluate the predicate for every known (at least major) version of OS X and then set the lower/upper bounds that way.

That said, if you're happy with it as is and want to move on, I'd be up for adding this functionality soon and submitting a PR.

**Comment by timsutton** [comment]
Another Q: any particular reason your pkginfo sets uninstallable to false? As far as I can see, the pkg components for this pkg all have sane payloads and so should uninstall using `removepackages` ok. (He says, not having actually tested it yet..)

**Comment by jessepeterson** [comment]
I merged that change to master. I also made you a contributor on this repo. Not sure when I'll get time next to update the Provider, but if you get time before me - go ahead and make the changes!

**Comment by jessepeterson** [comment]
Fixed the uninstallable deal. I was thinking about how to automatically install this update - it'd have to block on just about every Adobe app or anything that could possibly use this framework. Perhaps it needs to be a logout or reboot update?

**Comment by timsutton** [comment]
Oh, that was my other change I've used before. I set `RestartAction` to `RequireRestart` because it's also installing a kext. Although, when the installer is run via the GUI it doesn't ask me to restart, so I must have been assuming wrongly.

In that case I don't know what's the best default, though `RequireLogout` would make sense to me. No way you can build a comprehensive list of all possible apps in your recipe's defaults.

**Comment by jessepeterson** [comment]
Closing this issue as repository has moved to autopkg organization on GitHub.
